### ISSUE TITLE
Integrate with monaco ?

### ISSUE THREAD

**Issue by MangelMaxime** [nojaf/jason-to-thoth#1]
Should we use monaco for the input and output text ?

The benefit will be syntax coloration.

**Comment by nojaf** [comment]
There is still a weird `A` character I can't explain.
![image](https://user-images.githubusercontent.com/2621499/50546592-4e1a0a80-0c2a-11e9-9fb0-a39e4f8c566f.png)

**Comment by nojaf** [comment]
Turned out to be an encoding issue, was able to solve it by using [Encoding plugin](https://www.npmjs.com/package/webpack-encoding-plugin).

**Comment by MangelMaxime** [comment]
Awesome :)
